### ISSUE TITLE
StatusCodeError: 503

### ISSUE THREAD

**Issue by 4Ykw** [Greg-Griffith/Electron-Ecc-gui#4]
I am sure I had connectivity all the way to the daemon... but after a while, the wallet was throwing this message...even if I would click OK, another one will appear:
![ecc_bug1](https://user-images.githubusercontent.com/6281545/28240706-5c4c1e0c-69da-11e7-85b0-a7f3cc2135ac.png)

Closing and re-opening fixed the problem (have not tested leaving it open for the next time).

**Comment by Greg-Griffith** [comment]
fixed
